### ISSUE TITLE
Scraping para  obtener post de wordpress

### ISSUE THREAD

**Issue by juanpablocs** [frontend-labs/deploy#12]
Como estan migrando los posts de wordpress a archivos `md` de gatsby? Manualmente?

Me gustaria colaborar con una tarea que en base al id del post convierta el post en archivo `md`

Me comentan si les parece buena idea. 

Good Job !

**Comment by wilsson** [comment]
Hay un exportador de worpress que se esta usando que ya hace esa chamba

**Comment by juanpablocs** [comment]
Genial! cierro el ticket entonces.
